# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:
name: Victor Zheleznov
email: v.zheleznov@ed.ac.uk
description: Accompanying web-page for the JAES submission
baseurl: /jaes-modal-node # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: victorzheleznov
repository: "victorzheleznov/jaes-modal-node"
# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
classes: wide
markdown: kramdown

author:
  name: "Victor Zheleznov"

atom_feed:
  hide: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/victorzheleznov"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0009-0002-5534-505X"